#!/bin/bash

# This script is run every time your SageMaker instance starts, and is necessary because installed packages and cloned repos are not saved when the instance is stopped. To use, paste this script into the “start notebook” window when creating your lifecycle configuration, and set the variables for your GitHub username (case-sensitive), name, email address, password, and branch name (optional). Again, note that your local copy of the TrackML repo is not saved when the instance is stopped, so don’t forget to push to remote beforehand; otherwise you will lose changes.

REPOSITORY="TOsborn/TrackML"

CONDA_ENVIRONMENT="tensorflow_p36"

USERNAME=""
NAME=""
EMAIL=""
PASSWORD=""

# BRANCH=""  # optional

# exit immediately if a command exits with a non-zero status.
set -e

# get shell environment
source /home/ec2-user/.bashrc

# set git configuration
git config --global user.username $USERNAME
git config --global user.name $NAME
git config --global user.email $EMAIL

# activate tensorflow_p36
source activate $CONDA_ENVIRONMENT

# only contents of the folder SageMaker are visible in JupyterLab's file tree,
# so we do everything in this directory.
cd SageMaker

# install helper library
git clone https://github.com/LAL/trackml-library
pip install trackml-library/

git clone https://$USERNAME:$PASSWORD@github.com/$REPOSITORY
cd TrackML

# optionally create a branch and/or move to desired branch
# git branch $BRANCH
# git checkout $BRANCH
